# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('description', models.CharField(max_length=255, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'course',
                'verbose_name': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u8bfe\u7a0b\u8d44\u6e90\u540d\u79f0')),
                ('description', models.CharField(max_length=255, verbose_name='\u8bfe\u7a0b\u8d44\u6e90\u63cf\u8ff0')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourse.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'db_table': 'course_resource',
                'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90',
                'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u7ae0\u8282\u540d\u79f0')),
                ('description', models.CharField(max_length=255, verbose_name='\u7ae0\u8282\u63cf\u8ff0')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourse.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'db_table': 'lesson',
                'verbose_name': '\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u89c6\u9891\u540d\u79f0')),
                ('description', models.CharField(max_length=255, verbose_name='\u89c6\u9891\u63cf\u8ff0')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourse.Lesson', verbose_name='\u7ae0\u8282')),
            ],
            options={
                'db_table': 'video',
                'verbose_name': '\u89c6\u9891',
                'verbose_name_plural': '\u89c6\u9891',
            },
        ),
    ]
