# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u6d88\u606f\u540d\u79f0')),
                ('description', models.CharField(max_length=64, null=True, verbose_name='\u6d88\u606f\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'mesaget',
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
        ),
    ]
